name: Run Kobo Data Pipeline

on:
  # Programar ejecución cuatro veces al día
  schedule:
    - cron: "0 14 * * *" # 8:00 AM CST (14:00 UTC)
    - cron: "0 18 * * *" # 12:00 PM CST (18:00 UTC)
    - cron: "0 22 * * *" # 4:00 PM CST (22:00 UTC)
    - cron: "0 2 * * *"  # 8:00 PM CST (2:00 AM UTC siguiente día)

  # Permitir ejecución manual
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar entorno R
    - name: Set up R environment
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: "4.3.1"

    # 3. Instalar dependencias de sistema necesarias para algunos paquetes R
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    # 4. Instalar paquetes R y ejecutar el script maestro
    - name: Install R dependencies and run the pipeline
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        EMAIL: ${{ secrets.EMAIL }}
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
      run: |
        # Instalar pacman para manejar dependencias R
        Rscript -e "if (!require('pacman')) install.packages('pacman', repos='https://cloud.r-project.org')"
        # Instalar todos los paquetes necesarios declarados en el script
        Rscript -e "pacman::p_load(haven, labelled, tidyr, dplyr, readr, lubridate, googlesheets4, gargle, robotoolbox, openssl, dotenv, stringr, writexl, readxl)"
        # Ejecutar el script maestro
        Rscript IFC_master_script.R


