name: Run Kobo Data Pipeline

on:
  # Programar ejecución dos veces al día
  schedule:
    - cron: "0 6,18 * * *" # Ejecutar a las 6 AM y 6 PM UTC

  # Permitir ejecución manual
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instalar dependencias del sistema operativo
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      # 3. Configurar entorno R
      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3.1"

      # 4. Instalar paquetes y ejecutar el script maestro
      - name: Install dependencies and run master script
        run: |
          Rscript -e "install.packages('pacman', repos='https://cloud.r-project.org')"
          Rscript -e "pacman::p_load(haven, labelled, tidyr, dplyr, readr, lubridate, googlesheets4, gargle, robotoolbox, openssl, dotenv, stringr, writexl, readxl)"
          Rscript IFC_master_script.R
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          EMAIL: ${{ secrets.EMAIL }}
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
